import type {
  AdminStats,
  AdminUser,
  PropertyApprovalItem,
  VerificationRequest,
  Report,
  FraudAlert,
  RevenueRecord,
  ContentModerationItem,
} from "@/types";

// ─── Admin Stats ─────────────────────────────────────────────────────────────

export const MOCK_ADMIN_STATS: AdminStats = {
  total_users: 3842,
  new_users_today: 24,
  new_users_week: 187,
  total_landlords: 412,
  total_tenants: 3430,
  total_properties: 986,
  pending_approvals: 14,
  pending_verifications: 7,
  total_revenue: 284500,
  revenue_this_month: 48200,
  open_reports: 9,
  fraud_alerts: 3,
  monthly_signups: [
    { month: "Dec", tenants: 210, landlords: 28 },
    { month: "Jan", tenants: 265, landlords: 34 },
    { month: "Feb", tenants: 310, landlords: 41 },
    { month: "Mar", tenants: 288, landlords: 38 },
    { month: "Apr", tenants: 342, landlords: 52 },
    { month: "May", tenants: 398, landlords: 61 },
  ],
  daily_revenue: [
    { date: "Mon", amount: 7200 },
    { date: "Tue", amount: 5400 },
    { date: "Wed", amount: 8100 },
    { date: "Thu", amount: 6300 },
    { date: "Fri", amount: 9800 },
    { date: "Sat", amount: 11200 },
    { date: "Sun", amount: 4200 },
  ],
  property_types: [
    { type: "Hostel", count: 312 },
    { type: "Bedsitter", count: 248 },
    { type: "One Bedroom", count: 186 },
    { type: "Studio", count: 142 },
    { type: "Two Bedroom", count: 68 },
    { type: "Shared Room", count: 30 },
  ],
};

// ─── Admin Users ──────────────────────────────────────────────────────────────

export const MOCK_ADMIN_USERS: AdminUser[] = [
  {
    id: "u1",
    email: "james.mwangi@students.ku.ac.ke",
    full_name: "James Mwangi",
    avatar_url: null,
    phone: "+254 701 234 567",
    role: "tenant",
    status: "active",
    is_verified: true,
    listings_count: 0,
    bookings_count: 4,
    last_sign_in: "2026-05-22T08:30:00Z",
    created_at: "2025-09-01T10:00:00Z",
    flags: 0,
  },
  {
    id: "u2",
    email: "grace.njeri@gmail.com",
    full_name: "Grace Njeri",
    avatar_url: null,
    phone: "+254 722 345 678",
    role: "landlord",
    status: "active",
    is_verified: true,
    listings_count: 6,
    bookings_count: 23,
    last_sign_in: "2026-05-22T11:00:00Z",
    created_at: "2025-07-14T09:00:00Z",
    flags: 0,
  },
  {
    id: "u3",
    email: "peter.kamau@students.ku.ac.ke",
    full_name: "Peter Kamau",
    avatar_url: null,
    phone: "+254 733 456 789",
    role: "tenant",
    status: "suspended",
    is_verified: false,
    listings_count: 0,
    bookings_count: 1,
    last_sign_in: "2026-05-10T14:20:00Z",
    created_at: "2026-01-03T12:00:00Z",
    flags: 2,
  },
  {
    id: "u4",
    email: "mary.wanjiku@gmail.com",
    full_name: "Mary Wanjiku",
    avatar_url: null,
    phone: "+254 744 567 890",
    role: "landlord",
    status: "active",
    is_verified: true,
    listings_count: 12,
    bookings_count: 58,
    last_sign_in: "2026-05-21T16:45:00Z",
    created_at: "2025-05-20T08:00:00Z",
    flags: 0,
  },
  {
    id: "u5",
    email: "david.odhiambo@students.ku.ac.ke",
    full_name: "David Odhiambo",
    avatar_url: null,
    phone: null,
    role: "tenant",
    status: "active",
    is_verified: false,
    listings_count: 0,
    bookings_count: 2,
    last_sign_in: "2026-05-18T09:15:00Z",
    created_at: "2026-03-15T11:00:00Z",
    flags: 0,
  },
  {
    id: "u6",
    email: "spammer@fakemail.com",
    full_name: "John Doe",
    avatar_url: null,
    phone: null,
    role: "landlord",
    status: "banned",
    is_verified: false,
    listings_count: 3,
    bookings_count: 0,
    last_sign_in: "2026-04-30T23:00:00Z",
    created_at: "2026-04-28T06:00:00Z",
    flags: 5,
  },
  {
    id: "u7",
    email: "sarah.achieng@students.ku.ac.ke",
    full_name: "Sarah Achieng",
    avatar_url: null,
    phone: "+254 755 678 901",
    role: "tenant",
    status: "active",
    is_verified: true,
    listings_count: 0,
    bookings_count: 3,
    last_sign_in: "2026-05-22T07:00:00Z",
    created_at: "2025-08-22T13:00:00Z",
    flags: 0,
  },
  {
    id: "u8",
    email: "hassan.ali@gmail.com",
    full_name: "Hassan Ali",
    avatar_url: null,
    phone: "+254 766 789 012",
    role: "landlord",
    status: "active",
    is_verified: false,
    listings_count: 4,
    bookings_count: 11,
    last_sign_in: "2026-05-20T10:00:00Z",
    created_at: "2026-02-10T15:00:00Z",
    flags: 1,
  },
];

// ─── Property Approvals ───────────────────────────────────────────────────────

export const MOCK_PROPERTY_APPROVALS: PropertyApprovalItem[] = [
  {
    id: "pa1",
    property_id: "prop-new-1",
    landlord_id: "u8",
    status: "pending",
    reviewer_id: null,
    reviewer_note: null,
    submitted_at: "2026-05-22T06:00:00Z",
    reviewed_at: null,
    property: {
      id: "prop-new-1",
      landlord_id: "u8",
      title: "Modern Bedsitter Near KU Main Gate",
      description: "Fully furnished bedsitter with DSTV, WiFi, and 24/7 security.",
      type: "bedsitter",
      price: 12000,
      price_period: "per_month",
      location: "Thika Road, Ruiru",
      area: "Ruiru",
      latitude: -1.147, longitude: 36.96,
      bedrooms: 0, bathrooms: 1, max_occupants: 2,
      furnishing: "furnished",
      amenities: ["wifi", "water", "electricity", "security", "dstv"],
      rules: ["No smoking", "No pets"],
      is_available: true, is_verified: false, is_featured: false,
      views_count: 0, distance_from_campus: 0.4, gender_preference: "any",
      created_at: "2026-05-22T06:00:00Z", updated_at: "2026-05-22T06:00:00Z",
      images: [{ id: "img1", property_id: "prop-new-1", url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400", is_primary: true, sort_order: 0 }],
    },
    landlord: {
      id: "u8", email: "hassan.ali@gmail.com", full_name: "Hassan Ali",
      avatar_url: null, phone: "+254 766 789 012", role: "landlord",
      is_verified: false, created_at: "2026-02-10T15:00:00Z",
    },
  },
  {
    id: "pa2",
    property_id: "prop-new-2",
    landlord_id: "u2",
    status: "pending",
    reviewer_id: null,
    reviewer_note: null,
    submitted_at: "2026-05-21T14:30:00Z",
    reviewed_at: null,
    property: {
      id: "prop-new-2",
      landlord_id: "u2",
      title: "Spacious Hostel Room — 4 Units Available",
      description: "Large hostel rooms with shared bathrooms and kitchen.",
      type: "hostel",
      price: 7500,
      price_period: "per_month",
      location: "Kahawa West",
      area: "Kahawa West",
      latitude: -1.182, longitude: 36.938,
      bedrooms: 1, bathrooms: 1, max_occupants: 1,
      furnishing: "semi_furnished",
      amenities: ["water", "electricity", "security"],
      rules: ["Students only", "No noise after 10pm"],
      is_available: true, is_verified: false, is_featured: false,
      views_count: 0, distance_from_campus: 1.2, gender_preference: "female",
      created_at: "2026-05-21T14:30:00Z", updated_at: "2026-05-21T14:30:00Z",
      images: [{ id: "img2", property_id: "prop-new-2", url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400", is_primary: true, sort_order: 0 }],
    },
    landlord: {
      id: "u2", email: "grace.njeri@gmail.com", full_name: "Grace Njeri",
      avatar_url: null, phone: "+254 722 345 678", role: "landlord",
      is_verified: true, created_at: "2025-07-14T09:00:00Z",
    },
  },
  {
    id: "pa3",
    property_id: "prop-new-3",
    landlord_id: "u6",
    status: "flagged",
    reviewer_id: "admin-1",
    reviewer_note: "Images appear to be stolen from another listing. Awaiting landlord response.",
    submitted_at: "2026-05-20T09:00:00Z",
    reviewed_at: "2026-05-20T11:00:00Z",
    property: {
      id: "prop-new-3",
      landlord_id: "u6",
      title: "Luxury Studio — Too Good To Be True",
      description: "Luxury studio apartment near university.",
      type: "studio",
      price: 5000,
      price_period: "per_month",
      location: "Kahawa Sukari",
      area: "Kahawa Sukari",
      latitude: -1.19, longitude: 36.93,
      bedrooms: 0, bathrooms: 1, max_occupants: 1,
      furnishing: "furnished",
      amenities: ["wifi", "gym", "pool", "security"],
      rules: [],
      is_available: true, is_verified: false, is_featured: false,
      views_count: 12, distance_from_campus: 0.8, gender_preference: "any",
      created_at: "2026-05-20T09:00:00Z", updated_at: "2026-05-20T09:00:00Z",
      images: [],
    },
    landlord: {
      id: "u6", email: "spammer@fakemail.com", full_name: "John Doe",
      avatar_url: null, phone: null, role: "landlord",
      is_verified: false, created_at: "2026-04-28T06:00:00Z",
    },
  },
  {
    id: "pa4",
    property_id: "prop-new-4",
    landlord_id: "u4",
    status: "approved",
    reviewer_id: "admin-1",
    reviewer_note: "Verified. Meets all quality standards.",
    submitted_at: "2026-05-19T10:00:00Z",
    reviewed_at: "2026-05-19T12:00:00Z",
    property: {
      id: "prop-new-4",
      landlord_id: "u4",
      title: "One Bedroom in Thika Road",
      description: "Clean one bedroom apartment.",
      type: "one_bedroom",
      price: 18000,
      price_period: "per_month",
      location: "Roysambu",
      area: "Roysambu",
      latitude: -1.21, longitude: 36.88,
      bedrooms: 1, bathrooms: 1, max_occupants: 2,
      furnishing: "semi_furnished",
      amenities: ["water", "electricity", "parking"],
      rules: ["No smoking"],
      is_available: true, is_verified: true, is_featured: false,
      views_count: 45, distance_from_campus: 3.5, gender_preference: "any",
      created_at: "2026-05-19T10:00:00Z", updated_at: "2026-05-19T12:00:00Z",
      images: [],
    },
    landlord: {
      id: "u4", email: "mary.wanjiku@gmail.com", full_name: "Mary Wanjiku",
      avatar_url: null, phone: "+254 744 567 890", role: "landlord",
      is_verified: true, created_at: "2025-05-20T08:00:00Z",
    },
  },
];

// ─── Verification Requests ────────────────────────────────────────────────────

export const MOCK_VERIFICATION_REQUESTS: VerificationRequest[] = [
  {
    id: "vr1",
    user_id: "u8",
    property_id: "prop-new-1",
    type: "property",
    status: "pending",
    documents: [
      { name: "Title Deed", url: "#" },
      { name: "ID Copy", url: "#" },
    ],
    notes: "Please expedite — I have 4 tenants waiting.",
    reviewer_id: null,
    reviewer_note: null,
    submitted_at: "2026-05-22T07:00:00Z",
    reviewed_at: null,
    user: {
      id: "u8", email: "hassan.ali@gmail.com", full_name: "Hassan Ali",
      avatar_url: null, phone: "+254 766 789 012", role: "landlord",
      is_verified: false, created_at: "2026-02-10T15:00:00Z",
    },
  },
  {
    id: "vr2",
    user_id: "u5",
    property_id: null,
    type: "student",
    status: "pending",
    documents: [
      { name: "Student ID", url: "#" },
      { name: "Admission Letter", url: "#" },
    ],
    notes: null,
    reviewer_id: null,
    reviewer_note: null,
    submitted_at: "2026-05-21T15:00:00Z",
    reviewed_at: null,
    user: {
      id: "u5", email: "david.odhiambo@students.ku.ac.ke", full_name: "David Odhiambo",
      avatar_url: null, phone: null, role: "tenant",
      is_verified: false, created_at: "2026-03-15T11:00:00Z",
    },
  },
  {
    id: "vr3",
    user_id: "u2",
    property_id: null,
    type: "landlord",
    status: "approved",
    documents: [{ name: "KRA PIN Certificate", url: "#" }],
    notes: null,
    reviewer_id: "admin-1",
    reviewer_note: "All documents verified.",
    submitted_at: "2025-07-20T10:00:00Z",
    reviewed_at: "2025-07-21T09:00:00Z",
    user: {
      id: "u2", email: "grace.njeri@gmail.com", full_name: "Grace Njeri",
      avatar_url: null, phone: "+254 722 345 678", role: "landlord",
      is_verified: true, created_at: "2025-07-14T09:00:00Z",
    },
  },
];

// ─── Reports ──────────────────────────────────────────────────────────────────

export const MOCK_REPORTS: Report[] = [
  {
    id: "rep1",
    reporter_id: "u1",
    target_id: "prop-new-3",
    target_type: "property",
    reason: "Fake listing",
    description: "This listing has photos stolen from another website. The price is way too low and the landlord is unresponsive.",
    status: "investigating",
    moderator_id: "admin-1",
    moderator_note: "Confirmed duplicate images. Flagging listing for review.",
    created_at: "2026-05-21T10:00:00Z",
    resolved_at: null,
    reporter: {
      id: "u1", email: "james.mwangi@students.ku.ac.ke", full_name: "James Mwangi",
      avatar_url: null, phone: "+254 701 234 567", role: "tenant",
      is_verified: true, created_at: "2025-09-01T10:00:00Z",
    },
  },
  {
    id: "rep2",
    reporter_id: "u7",
    target_id: "u6",
    target_type: "profile",
    reason: "Fraudulent landlord",
    description: "Collected deposit and disappeared. Did not provide keys.",
    status: "open",
    moderator_id: null,
    moderator_note: null,
    created_at: "2026-05-22T08:00:00Z",
    resolved_at: null,
    reporter: {
      id: "u7", email: "sarah.achieng@students.ku.ac.ke", full_name: "Sarah Achieng",
      avatar_url: null, phone: "+254 755 678 901", role: "tenant",
      is_verified: true, created_at: "2025-08-22T13:00:00Z",
    },
  },
  {
    id: "rep3",
    reporter_id: "u2",
    target_id: "rev-99",
    target_type: "review",
    reason: "False review",
    description: "This reviewer never lived in my property. The review is fake and malicious.",
    status: "resolved",
    moderator_id: "admin-1",
    moderator_note: "Review removed after investigation. No booking record found.",
    created_at: "2026-05-10T12:00:00Z",
    resolved_at: "2026-05-11T09:00:00Z",
    reporter: {
      id: "u2", email: "grace.njeri@gmail.com", full_name: "Grace Njeri",
      avatar_url: null, phone: "+254 722 345 678", role: "landlord",
      is_verified: true, created_at: "2025-07-14T09:00:00Z",
    },
  },
];

// ─── Fraud Alerts ─────────────────────────────────────────────────────────────

export const MOCK_FRAUD_ALERTS: FraudAlert[] = [
  {
    id: "fa1",
    user_id: "u6",
    property_id: "prop-new-3",
    type: "fake_images",
    severity: "high",
    description: "Reverse image search confirms 3 of 4 listing photos are from a UK property website.",
    evidence: ["Image hash match: img_001 → rightmove.co.uk/property/123", "Image hash match: img_002 → zoopla.co.uk/property/456"],
    is_resolved: false,
    created_at: "2026-05-20T11:30:00Z",
    user: {
      id: "u6", email: "spammer@fakemail.com", full_name: "John Doe",
      avatar_url: null, phone: null, role: "landlord",
      is_verified: false, created_at: "2026-04-28T06:00:00Z",
    },
  },
  {
    id: "fa2",
    user_id: "u3",
    property_id: null,
    type: "spam",
    severity: "medium",
    description: "User sent 47 identical inquiry messages in 2 hours using automation.",
    evidence: ["47 messages sent between 2026-05-10 02:00–04:00", "All messages identical", "IP flagged in fraud database"],
    is_resolved: false,
    created_at: "2026-05-10T04:15:00Z",
    user: {
      id: "u3", email: "peter.kamau@students.ku.ac.ke", full_name: "Peter Kamau",
      avatar_url: null, phone: "+254 733 456 789", role: "tenant",
      is_verified: false, created_at: "2026-01-03T12:00:00Z",
    },
  },
  {
    id: "fa3",
    user_id: "u6",
    property_id: null,
    type: "identity_fraud",
    severity: "critical",
    description: "User profile name and ID documents don't match. Facial recognition mismatch.",
    evidence: ["ID document: 'Ali Omondi'", "Registered name: 'John Doe'", "Face ID confidence: 12%"],
    is_resolved: false,
    created_at: "2026-05-01T09:00:00Z",
    user: {
      id: "u6", email: "spammer@fakemail.com", full_name: "John Doe",
      avatar_url: null, phone: null, role: "landlord",
      is_verified: false, created_at: "2026-04-28T06:00:00Z",
    },
  },
];

// ─── Revenue Records ──────────────────────────────────────────────────────────

export const MOCK_REVENUE: RevenueRecord[] = [
  {
    id: "rev1",
    user_id: "u4",
    type: "subscription",
    amount: 2999,
    currency: "KES",
    status: "completed",
    description: "Pro Landlord Plan — Monthly",
    created_at: "2026-05-01T09:00:00Z",
    user: {
      id: "u4", email: "mary.wanjiku@gmail.com", full_name: "Mary Wanjiku",
      avatar_url: null, phone: "+254 744 567 890", role: "landlord",
      is_verified: true, created_at: "2025-05-20T08:00:00Z",
    },
  },
  {
    id: "rev2",
    user_id: "u2",
    type: "feature_boost",
    amount: 1500,
    currency: "KES",
    status: "completed",
    description: "Featured listing boost — 7 days",
    created_at: "2026-05-10T11:00:00Z",
    user: {
      id: "u2", email: "grace.njeri@gmail.com", full_name: "Grace Njeri",
      avatar_url: null, phone: "+254 722 345 678", role: "landlord",
      is_verified: true, created_at: "2025-07-14T09:00:00Z",
    },
  },
  {
    id: "rev3",
    user_id: "u8",
    type: "verification_fee",
    amount: 500,
    currency: "KES",
    status: "completed",
    description: "Property verification fee",
    created_at: "2026-05-14T14:00:00Z",
    user: {
      id: "u8", email: "hassan.ali@gmail.com", full_name: "Hassan Ali",
      avatar_url: null, phone: "+254 766 789 012", role: "landlord",
      is_verified: false, created_at: "2026-02-10T15:00:00Z",
    },
  },
  {
    id: "rev4",
    user_id: "u4",
    type: "subscription",
    amount: 2999,
    currency: "KES",
    status: "completed",
    description: "Pro Landlord Plan — Monthly",
    created_at: "2026-04-01T09:00:00Z",
    user: {
      id: "u4", email: "mary.wanjiku@gmail.com", full_name: "Mary Wanjiku",
      avatar_url: null, phone: "+254 744 567 890", role: "landlord",
      is_verified: true, created_at: "2025-05-20T08:00:00Z",
    },
  },
  {
    id: "rev5",
    user_id: "u2",
    type: "subscription",
    amount: 2999,
    currency: "KES",
    status: "completed",
    description: "Pro Landlord Plan — Monthly",
    created_at: "2026-05-01T10:00:00Z",
    user: {
      id: "u2", email: "grace.njeri@gmail.com", full_name: "Grace Njeri",
      avatar_url: null, phone: "+254 722 345 678", role: "landlord",
      is_verified: true, created_at: "2025-07-14T09:00:00Z",
    },
  },
];

// ─── Content Moderation ───────────────────────────────────────────────────────

export const MOCK_CONTENT_MODERATION: ContentModerationItem[] = [
  {
    id: "cm1",
    content_type: "review",
    content_id: "rev-42",
    content_preview: "This landlord is a thief! He stole my deposit and threatened me when I asked for it back.",
    reason: "Potentially defamatory content flagged by AI",
    status: "pending",
    created_at: "2026-05-22T09:00:00Z",
    author: {
      id: "u1", email: "james.mwangi@students.ku.ac.ke", full_name: "James Mwangi",
      avatar_url: null, phone: "+254 701 234 567", role: "tenant",
      is_verified: true, created_at: "2025-09-01T10:00:00Z",
    },
  },
  {
    id: "cm2",
    content_type: "property",
    content_id: "prop-new-3",
    content_preview: "Luxury studio apartment near university — Fully furnished, pool, gym — KES 5,000/month",
    reason: "Price anomaly: 400% below market rate",
    status: "pending",
    created_at: "2026-05-22T06:30:00Z",
    author: {
      id: "u6", email: "spammer@fakemail.com", full_name: "John Doe",
      avatar_url: null, phone: null, role: "landlord",
      is_verified: false, created_at: "2026-04-28T06:00:00Z",
    },
  },
  {
    id: "cm3",
    content_type: "message",
    content_id: "msg-77",
    content_preview: "Send me KES 5,000 as deposit via M-Pesa before viewing. I'll send you the details after...",
    reason: "Advance fee fraud pattern detected",
    status: "pending",
    created_at: "2026-05-21T17:00:00Z",
    author: {
      id: "u3", email: "peter.kamau@students.ku.ac.ke", full_name: "Peter Kamau",
      avatar_url: null, phone: "+254 733 456 789", role: "tenant",
      is_verified: false, created_at: "2026-01-03T12:00:00Z",
    },
  },
  {
    id: "cm4",
    content_type: "review",
    content_id: "rev-101",
    content_preview: "Great place! Clean, quiet, and the landlord is very responsive. Would recommend.",
    reason: "Suspicious posting pattern: 12 5-star reviews in 24h",
    status: "approved",
    created_at: "2026-05-18T12:00:00Z",
    author: {
      id: "u5", email: "david.odhiambo@students.ku.ac.ke", full_name: "David Odhiambo",
      avatar_url: null, phone: null, role: "tenant",
      is_verified: false, created_at: "2026-03-15T11:00:00Z",
    },
  },
];
