import type { Property } from "@/types";

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "1", landlord_id: "l1",
    title: "Modern Bedsitter Near Machakos University",
    description: "Clean, spacious bedsitter with high-speed WiFi, 24hr water supply, and a dedicated study desk. Quiet compound perfect for students. Shared bathroom with hot water.",
    type: "bedsitter", price: 5500, price_period: "per_month",
    location: "Gate B Road, Machakos Town", area: "Machakos Town",
    latitude: -1.5177, longitude: 37.2634, bedrooms: 0, bathrooms: 1, max_occupants: 2,
    furnishing: "semi_furnished",
    amenities: ["WiFi", "Water 24/7", "Security Guard", "Study Room"],
    rules: ["No smoking", "No loud music after 10pm"],
    is_available: true, is_verified: true, is_featured: true,
    views_count: 243, distance_from_campus: 0.3, gender_preference: "female",
    created_at: new Date(Date.now() - 2 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i1a", property_id: "1", url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800", is_primary: true, order: 0 },
      { id: "i1b", property_id: "1", url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800", is_primary: false, order: 1 },
      { id: "i1c", property_id: "1", url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800", is_primary: false, order: 2 },
    ],
    landlord: { id: "l1", email: "landlord1@gmail.com", full_name: "Peter Mwangi", avatar_url: null, phone: "+254712345678", role: "landlord", is_verified: true, created_at: "" },
  },
  {
    id: "2", landlord_id: "l2",
    title: "Cosy Hostel Room — All Inclusive Package",
    description: "Well-maintained hostel room with all utilities included. Features a dedicated study hall, laundry area, backup generator, and secure parking. 5-minute walk from MKU main gate.",
    type: "hostel", price: 3500, price_period: "per_month",
    location: "Kenyatta Avenue, Machakos Town", area: "Machakos Town",
    latitude: -1.52, longitude: 37.27, bedrooms: 0, bathrooms: 1, max_occupants: 4,
    furnishing: "furnished",
    amenities: ["WiFi", "Laundry", "Study Room", "Backup Power", "Water 24/7"],
    rules: ["Curfew at 11pm"],
    is_available: true, is_verified: true, is_featured: true,
    views_count: 389, distance_from_campus: 0.5, gender_preference: "any",
    created_at: new Date(Date.now() - 5 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i2a", property_id: "2", url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800", is_primary: true, order: 0 },
      { id: "i2b", property_id: "2", url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800", is_primary: false, order: 1 },
    ],
    landlord: { id: "l2", email: "landlord2@gmail.com", full_name: "Grace Mutua", avatar_url: null, phone: "+254722345678", role: "landlord", is_verified: true, created_at: "" },
  },
  {
    id: "3", landlord_id: "l3",
    title: "Spacious 1-Bedroom Apartment with Balcony",
    description: "Bright and spacious one-bedroom apartment ideal for young professionals or couples. Features a private balcony with Machakos town views, covered parking, and 24hr security.",
    type: "one_bedroom", price: 12000, price_period: "per_month",
    location: "Stadium Road, Machakos Town", area: "Machakos Town",
    latitude: -1.515, longitude: 37.26, bedrooms: 1, bathrooms: 1, max_occupants: 2,
    furnishing: "semi_furnished",
    amenities: ["Parking", "Balcony", "Water 24/7", "Security Guard", "CCTV"],
    rules: ["No pets", "No smoking indoors"],
    is_available: true, is_verified: false, is_featured: true,
    views_count: 312, distance_from_campus: 1.2, gender_preference: "any",
    created_at: new Date(Date.now() - 7 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i3a", property_id: "3", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800", is_primary: true, order: 0 },
      { id: "i3b", property_id: "3", url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800", is_primary: false, order: 1 },
    ],
    landlord: { id: "l3", email: "landlord3@gmail.com", full_name: "James Kioko", avatar_url: null, phone: "+254733345678", role: "landlord", is_verified: false, created_at: "" },
  },
  {
    id: "4", landlord_id: "l4",
    title: "Premium Studio Apartment — Athi River",
    description: "Modern studio apartment in the heart of Athi River. Access to an onsite gym and swimming pool. High ceilings, open-plan design, and fully equipped kitchen.",
    type: "studio", price: 18000, price_period: "per_month",
    location: "Industrial Area, Athi River", area: "Athi River",
    latitude: -1.46, longitude: 36.98, bedrooms: 0, bathrooms: 1, max_occupants: 2,
    furnishing: "furnished",
    amenities: ["Gym", "Swimming Pool", "WiFi", "Parking", "CCTV", "Kitchen"],
    rules: ["No parties"],
    is_available: true, is_verified: true, is_featured: false,
    views_count: 98, distance_from_campus: 5.0, gender_preference: "any",
    created_at: new Date(Date.now() - 10 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i4a", property_id: "4", url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800", is_primary: true, order: 0 },
    ],
    landlord: { id: "l4", email: "landlord4@gmail.com", full_name: "Susan Waweru", avatar_url: null, phone: "+254744345678", role: "landlord", is_verified: true, created_at: "" },
  },
  {
    id: "5", landlord_id: "l5",
    title: "Budget Shared Room — 5 Mins from Campus Gate",
    description: "Most affordable option for students on a tight budget. Just 100m from MKU Gate A. Clean shared rooms with lockers, WiFi, and 24hr water. Strict no-noise policy.",
    type: "shared_room", price: 2500, price_period: "per_month",
    location: "University Road, Machakos Town", area: "Machakos Town",
    latitude: -1.519, longitude: 37.265, bedrooms: 0, bathrooms: 1, max_occupants: 3,
    furnishing: "furnished",
    amenities: ["WiFi", "Water 24/7", "Near Campus", "Security Guard"],
    rules: ["No alcohol", "Curfew at 10pm", "No overnight guests"],
    is_available: true, is_verified: true, is_featured: false,
    views_count: 521, distance_from_campus: 0.1, gender_preference: "male",
    created_at: new Date(Date.now() - 3 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i5a", property_id: "5", url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800", is_primary: true, order: 0 },
    ],
    landlord: { id: "l5", email: "landlord5@gmail.com", full_name: "John Musyoka", avatar_url: null, phone: "+254755345678", role: "landlord", is_verified: true, created_at: "" },
  },
  {
    id: "6", landlord_id: "l6",
    title: "2-Bedroom Family Apartment — Muvuti",
    description: "Ideal for couples, small families, or two students splitting rent. Features a private garden, covered parking, and new CCTV installation. Quiet residential estate.",
    type: "two_bedroom", price: 22000, price_period: "per_month",
    location: "Muvuti Area, Machakos Town", area: "Machakos Town",
    latitude: -1.524, longitude: 37.27, bedrooms: 2, bathrooms: 2, max_occupants: 4,
    furnishing: "semi_furnished",
    amenities: ["Parking", "Garden", "Water 24/7", "CCTV", "Security Guard"],
    rules: ["No smoking indoors", "No loud music"],
    is_available: true, is_verified: false, is_featured: false,
    views_count: 167, distance_from_campus: 2.0, gender_preference: "any",
    created_at: new Date(Date.now() - 14 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i6a", property_id: "6", url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800", is_primary: true, order: 0 },
    ],
    landlord: { id: "l6", email: "landlord6@gmail.com", full_name: "Mary Ndunge", avatar_url: null, phone: "+254766345678", role: "landlord", is_verified: false, created_at: "" },
  },
  {
    id: "7", landlord_id: "l7",
    title: "Premium Ladies Hostel — Gated Compound",
    description: "Secure ladies-only hostel with biometric access, CCTV, and a resident caretaker. Includes WiFi, laundry, and a rooftop terrace. Walking distance to MKU.",
    type: "hostel", price: 4500, price_period: "per_month",
    location: "Mlimani Road, Machakos Town", area: "Machakos Town",
    latitude: -1.518, longitude: 37.266, bedrooms: 0, bathrooms: 1, max_occupants: 2,
    furnishing: "furnished",
    amenities: ["WiFi", "Laundry", "CCTV", "Security Guard", "Water 24/7", "Backup Power"],
    rules: ["Female tenants only", "No male overnight guests", "Curfew at midnight"],
    is_available: true, is_verified: true, is_featured: true,
    views_count: 278, distance_from_campus: 0.2, gender_preference: "female",
    created_at: new Date(Date.now() - 1 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i7a", property_id: "7", url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800", is_primary: true, order: 0 },
      { id: "i7b", property_id: "7", url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800", is_primary: false, order: 1 },
    ],
    landlord: { id: "l7", email: "landlord7@gmail.com", full_name: "Agnes Kamau", avatar_url: null, phone: "+254777345678", role: "landlord", is_verified: true, created_at: "" },
  },
  {
    id: "8", landlord_id: "l8",
    title: "Self-Contained Bedsitter — Mlolongo",
    description: "Modern bedsitter in Mlolongo's upcoming Sunrise Estate. Tiled floors, fitted wardrobes, and a private en-suite bathroom. Close to SGR Syokimau station.",
    type: "bedsitter", price: 7000, price_period: "per_month",
    location: "Sunrise Estate, Mlolongo", area: "Mlolongo",
    latitude: -1.39, longitude: 36.97, bedrooms: 0, bathrooms: 1, max_occupants: 2,
    furnishing: "semi_furnished",
    amenities: ["Water 24/7", "Security Guard", "Parking", "Public Transport"],
    rules: ["No pets"],
    is_available: true, is_verified: true, is_featured: false,
    views_count: 145, distance_from_campus: 8.0, gender_preference: "any",
    created_at: new Date(Date.now() - 8 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i8a", property_id: "8", url: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800", is_primary: true, order: 0 },
    ],
    landlord: { id: "l8", email: "landlord8@gmail.com", full_name: "Paul Mutuku", avatar_url: null, phone: "+254788345678", role: "landlord", is_verified: true, created_at: "" },
  },
  {
    id: "9", landlord_id: "l9",
    title: "Affordable Gents Hostel — Near MKU Gate A",
    description: "Budget-friendly male hostel right on the university road. Shared rooms with individual lockers. Free WiFi, borehole water, and daily cleaning service included.",
    type: "hostel", price: 2800, price_period: "per_month",
    location: "Gate A Road, Machakos Town", area: "Machakos Town",
    latitude: -1.5185, longitude: 37.264, bedrooms: 0, bathrooms: 1, max_occupants: 6,
    furnishing: "furnished",
    amenities: ["WiFi", "Water 24/7", "Near Campus", "Security Guard", "Laundry"],
    rules: ["Male only", "No alcohol on premises"],
    is_available: true, is_verified: true, is_featured: false,
    views_count: 334, distance_from_campus: 0.4, gender_preference: "male",
    created_at: new Date(Date.now() - 6 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i9a", property_id: "9", url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800", is_primary: true, order: 0 },
    ],
    landlord: { id: "l9", email: "landlord9@gmail.com", full_name: "David Kimani", avatar_url: null, phone: "+254799345678", role: "landlord", is_verified: true, created_at: "" },
  },
  {
    id: "10", landlord_id: "l10",
    title: "Executive Studio — Syokimau Heights",
    description: "High-end studio apartment in the prestigious Syokimau Heights complex. Features a modern kitchenette, walk-in wardrobe, high-speed fibre internet, and stunning Nairobi skyline views.",
    type: "studio", price: 25000, price_period: "per_month",
    location: "Syokimau Heights, Syokimau", area: "Syokimau",
    latitude: -1.365, longitude: 36.916, bedrooms: 0, bathrooms: 1, max_occupants: 2,
    furnishing: "furnished",
    amenities: ["WiFi", "Parking", "CCTV", "Security Guard", "Gym", "Backup Power", "Kitchen"],
    rules: ["No smoking", "Professional tenants preferred"],
    is_available: true, is_verified: true, is_featured: true,
    views_count: 201, distance_from_campus: 12.0, gender_preference: "any",
    created_at: new Date(Date.now() - 4 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i10a", property_id: "10", url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800", is_primary: true, order: 0 },
      { id: "i10b", property_id: "10", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800", is_primary: false, order: 1 },
    ],
    landlord: { id: "l10", email: "landlord10@gmail.com", full_name: "Robert Omondi", avatar_url: null, phone: "+254700345678", role: "landlord", is_verified: true, created_at: "" },
  },
  {
    id: "11", landlord_id: "l11",
    title: "1-Bedroom Near Machakos Level 5 Hospital",
    description: "Conveniently located one-bedroom apartment near Machakos Level 5 Hospital. Ideal for medical staff or professionals. Includes parking, constant water, and a private store.",
    type: "one_bedroom", price: 9500, price_period: "per_month",
    location: "Hospital Road, Machakos Town", area: "Machakos Town",
    latitude: -1.521, longitude: 37.269, bedrooms: 1, bathrooms: 1, max_occupants: 2,
    furnishing: "semi_furnished",
    amenities: ["Parking", "Water 24/7", "Security Guard", "Public Transport"],
    rules: ["No subletting"],
    is_available: true, is_verified: false, is_featured: false,
    views_count: 88, distance_from_campus: 1.5, gender_preference: "any",
    created_at: new Date(Date.now() - 20 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i11a", property_id: "11", url: "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800", is_primary: true, order: 0 },
    ],
    landlord: { id: "l11", email: "landlord11@gmail.com", full_name: "Alice Mwende", avatar_url: null, phone: "+254711345678", role: "landlord", is_verified: false, created_at: "" },
  },
  {
    id: "12", landlord_id: "l12",
    title: "Modern Mixed Hostel — Athi River Town",
    description: "Purpose-built student hostel in Athi River with separate wings for male and female tenants. Common lounge, rooftop study area, and convenient access to EPZ industries.",
    type: "hostel", price: 3800, price_period: "per_month",
    location: "EPZ Road, Athi River", area: "Athi River",
    latitude: -1.458, longitude: 36.981, bedrooms: 0, bathrooms: 1, max_occupants: 4,
    furnishing: "furnished",
    amenities: ["WiFi", "Laundry", "Study Room", "Water 24/7", "Security Guard", "Public Transport"],
    rules: ["Quiet hours 10pm–6am"],
    is_available: false, is_verified: true, is_featured: false,
    views_count: 156, distance_from_campus: 4.0, gender_preference: "any",
    created_at: new Date(Date.now() - 15 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i12a", property_id: "12", url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800", is_primary: true, order: 0 },
    ],
    landlord: { id: "l12", email: "landlord12@gmail.com", full_name: "Kevin Otieno", avatar_url: null, phone: "+254721345678", role: "landlord", is_verified: true, created_at: "" },
  },
  {
    id: "13", landlord_id: "l13",
    title: "Budget Bedsitter — Kangundo Town",
    description: "Affordable bedsitter in the heart of Kangundo. Good for those commuting to Machakos or Nairobi. Shared ablutions, borehole water, and a small kitchen area.",
    type: "bedsitter", price: 4000, price_period: "per_month",
    location: "Market Road, Kangundo", area: "Kangundo",
    latitude: -1.246, longitude: 37.347, bedrooms: 0, bathrooms: 1, max_occupants: 2,
    furnishing: "unfurnished",
    amenities: ["Water 24/7", "Security Guard", "Public Transport"],
    rules: [],
    is_available: true, is_verified: false, is_featured: false,
    views_count: 62, distance_from_campus: 18.0, gender_preference: "any",
    created_at: new Date(Date.now() - 30 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i13a", property_id: "13", url: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800", is_primary: true, order: 0 },
    ],
    landlord: { id: "l13", email: "landlord13@gmail.com", full_name: "Nancy Wanjiku", avatar_url: null, phone: "+254731345678", role: "landlord", is_verified: false, created_at: "" },
  },
  {
    id: "14", landlord_id: "l7",
    title: "Single Room — Ladies Only, Near Campus",
    description: "Secure single occupancy room in a ladies-only compound. 300m from MKU Gate B. En-suite bathroom, wardrobe, study table, and WiFi included in rent.",
    type: "shared_room", price: 2000, price_period: "per_month",
    location: "Gate B Lane, Machakos Town", area: "Machakos Town",
    latitude: -1.5172, longitude: 37.2638, bedrooms: 0, bathrooms: 1, max_occupants: 1,
    furnishing: "furnished",
    amenities: ["WiFi", "Water 24/7", "Near Campus", "Security Guard", "CCTV"],
    rules: ["Female tenants only", "No cooking in room", "Curfew at 11pm"],
    is_available: true, is_verified: true, is_featured: false,
    views_count: 299, distance_from_campus: 0.3, gender_preference: "female",
    created_at: new Date(Date.now() - 9 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i14a", property_id: "14", url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800", is_primary: true, order: 0 },
    ],
    landlord: { id: "l7", email: "landlord7@gmail.com", full_name: "Agnes Kamau", avatar_url: null, phone: "+254777345678", role: "landlord", is_verified: true, created_at: "" },
  },
  {
    id: "15", landlord_id: "l14",
    title: "2-Bedroom Fully Furnished — Mlolongo Estate",
    description: "Spacious, fully furnished 2-bedroom apartment in a gated Mlolongo estate. New appliances, fibre internet, and access to a shared swimming pool. Ideal for families or professionals.",
    type: "two_bedroom", price: 28000, price_period: "per_month",
    location: "Green Valley Estate, Mlolongo", area: "Mlolongo",
    latitude: -1.388, longitude: 36.969, bedrooms: 2, bathrooms: 2, max_occupants: 4,
    furnishing: "furnished",
    amenities: ["WiFi", "Swimming Pool", "Parking", "CCTV", "Security Guard", "Garden", "Backup Power"],
    rules: ["No smoking", "Pets allowed with deposit"],
    is_available: true, is_verified: true, is_featured: false,
    views_count: 213, distance_from_campus: 9.0, gender_preference: "any",
    created_at: new Date(Date.now() - 12 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i15a", property_id: "15", url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800", is_primary: true, order: 0 },
      { id: "i15b", property_id: "15", url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800", is_primary: false, order: 1 },
    ],
    landlord: { id: "l14", email: "landlord14@gmail.com", full_name: "George Muthui", avatar_url: null, phone: "+254741345678", role: "landlord", is_verified: true, created_at: "" },
  },
  {
    id: "16", landlord_id: "l15",
    title: "Stylish Studio Loft — Machakos Town Centre",
    description: "Contemporary open-plan studio loft in the heart of Machakos Town. High ceilings, exposed brick walls, and floor-to-ceiling windows. Walking distance to all amenities.",
    type: "studio", price: 14000, price_period: "per_month",
    location: "Town Centre, Machakos Town", area: "Machakos Town",
    latitude: -1.516, longitude: 37.261, bedrooms: 0, bathrooms: 1, max_occupants: 2,
    furnishing: "semi_furnished",
    amenities: ["WiFi", "Water 24/7", "Security Guard", "Public Transport", "Backup Power"],
    rules: ["No parties", "Quiet hours after 11pm"],
    is_available: true, is_verified: true, is_featured: false,
    views_count: 178, distance_from_campus: 0.8, gender_preference: "any",
    created_at: new Date(Date.now() - 11 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i16a", property_id: "16", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800", is_primary: true, order: 0 },
    ],
    landlord: { id: "l15", email: "landlord15@gmail.com", full_name: "Faith Musau", avatar_url: null, phone: "+254751345678", role: "landlord", is_verified: true, created_at: "" },
  },
  {
    id: "17", landlord_id: "l16",
    title: "Ensuite Hostel Room — Campus View",
    description: "Premium ensuite hostel room with direct views of Machakos University. Brand new build with solar panels for hot water, fibre WiFi, and a spacious common lounge area.",
    type: "hostel", price: 5000, price_period: "per_month",
    location: "Campus View Road, Machakos Town", area: "Machakos Town",
    latitude: -1.5175, longitude: 37.267, bedrooms: 0, bathrooms: 1, max_occupants: 2,
    furnishing: "furnished",
    amenities: ["WiFi", "Water 24/7", "Near Campus", "Backup Power", "Security Guard", "Study Room"],
    rules: ["Curfew at midnight", "No alcohol"],
    is_available: false, is_verified: true, is_featured: false,
    views_count: 441, distance_from_campus: 0.6, gender_preference: "any",
    created_at: new Date(Date.now() - 25 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i17a", property_id: "17", url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800", is_primary: true, order: 0 },
    ],
    landlord: { id: "l16", email: "landlord16@gmail.com", full_name: "Bernard Mutia", avatar_url: null, phone: "+254761345678", role: "landlord", is_verified: true, created_at: "" },
  },
  {
    id: "18", landlord_id: "l17",
    title: "1-Bedroom Apartment — Athi River, Near Highway",
    description: "Well-maintained one-bedroom apartment minutes from the Nairobi–Mombasa highway. Ideal for EPZ workers and commuters. Kitchen fitted with gas cooker and water heater.",
    type: "one_bedroom", price: 15000, price_period: "per_month",
    location: "Highway Junction, Athi River", area: "Athi River",
    latitude: -1.464, longitude: 36.976, bedrooms: 1, bathrooms: 1, max_occupants: 2,
    furnishing: "semi_furnished",
    amenities: ["Parking", "Water 24/7", "Security Guard", "Kitchen", "Public Transport"],
    rules: ["No subletting"],
    is_available: true, is_verified: false, is_featured: false,
    views_count: 77, distance_from_campus: 3.5, gender_preference: "any",
    created_at: new Date(Date.now() - 18 * 24 * 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: "i18a", property_id: "18", url: "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800", is_primary: true, order: 0 },
    ],
    landlord: { id: "l17", email: "landlord17@gmail.com", full_name: "Samuel Nzeki", avatar_url: null, phone: "+254771345678", role: "landlord", is_verified: false, created_at: "" },
  },
];
